// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDumXdGJJ9nWDPRzxQCdg-maQh7mMDWBFc',
    appId: '1:782695805227:web:5afc864651934ce969956e',
    messagingSenderId: '782695805227',
    projectId: 'dapzo-prod',
    authDomain: 'dapzo-prod.firebaseapp.com',
    storageBucket: 'dapzo-prod.firebasestorage.app',
    measurementId: 'G-8T7EP6L1RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_TfkHdDnCyITmMeOmLGLZw91ivTHkzGU',
    appId: '1:782695805227:android:ce3c8b6296262e2469956e',
    messagingSenderId: '782695805227',
    projectId: 'dapzo-prod',
    storageBucket: 'dapzo-prod.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbr9yz-H_Y8TxhP-21T5V4DRuTeL26aK4',
    appId: '1:782695805227:ios:50d38e347a05f77b69956e',
    messagingSenderId: '782695805227',
    projectId: 'dapzo-prod',
    storageBucket: 'dapzo-prod.firebasestorage.app',
    iosBundleId: 'com.example.dapzo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbr9yz-H_Y8TxhP-21T5V4DRuTeL26aK4',
    appId: '1:782695805227:ios:50d38e347a05f77b69956e',
    messagingSenderId: '782695805227',
    projectId: 'dapzo-prod',
    storageBucket: 'dapzo-prod.firebasestorage.app',
    iosBundleId: 'com.example.dapzo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDumXdGJJ9nWDPRzxQCdg-maQh7mMDWBFc',
    appId: '1:782695805227:web:72537c7d29f100e269956e',
    messagingSenderId: '782695805227',
    projectId: 'dapzo-prod',
    authDomain: 'dapzo-prod.firebaseapp.com',
    storageBucket: 'dapzo-prod.firebasestorage.app',
    measurementId: 'G-DP9PYDV926',
  );
}
